### PR TITLE
Load recaptcha only when needed

### LINKED ISSUE #4: It's possible to open the register modal before grecaptcha is loaded
https://discuss.flarum.org/d/18399-friendsofflarum-recaptcha/17
https://discuss.flarum.org/d/12452-flagrow-direct-links/26

The google scripts loads asynchronously and adds another asynchronous script to the page.

When the signup modal is open programmatically, for example via the Direct Links extension, it's possible for https://github.com/FriendsOfFlarum/recaptcha/blob/7e73bbdbe3bff21202fdd7e0b250ab7e9fb2d5a6/js/src/forum/components/Recaptcha.js#L38 to run before `grecaptcha.execute()` is available, resulting in a `Uncaught ReferenceError: grecaptcha is not defined` error.

This results in a "something went wrong" message for the user and the signup modal doesn't open.

This might also happen when the signup modal is quickly open on a slow connection.

### LINKED ISSUE #17: reCAPTCHA javascript loads when not needed
When Looking at Google page insights: https://developers.google.com/speed/pagespeed/insights/

It shows that the recaptcha is loading on pages that do not use it. This slows down overall page load and effects SEO. 

I would love to see it only load when needed.

### PR DESCRIPTION
**Pull request by Nearata**
fixes #17 
fixes #4

### CODE REVIEW

File: js/src/forum/components/Recaptcha.js [hunk 1]
```diff
@@ -11,7 +11,28 @@ export default class Recaptcha extends Component {
...
+            app.recaptchaLoaded = true;
+
+            const script = document.createElement('script');
+            script.src = `https://www.recaptcha.net/recaptcha/api.js?hl=${app.translator.locale}&render=explicit`;
+            script.async = true;
+            script.defer = true;
+            script.onload = resolve;
+            document.body.appendChild(script);
+        }).then(() => {
+            const interval = setInterval(() => {
```
Comment (datitisev) [inline js/src/forum/components/Recaptcha.js:29]: Why is this interval here? Is it because you're setting `defer` to `true`? 

I'd rather not have this entire logic here - the NPM package `external-load` does a similar thing, and all you need is `load.js('...')` - it's used in fof/geoip (https://github.com/FriendsOfFlarum/geoip/blob/3849e7e13518f3a79ba834f6a37260647fa4ee13/js/src/forum/components/ZipCodeMap.js#L5)

Comment (Nearata) [reply js/src/forum/components/Recaptcha.js:29]: without it i get this

```js
Uncaught (in promise) TypeError: grecaptcha.render is not a function
    at RecaptchaState.render (RecaptchaState.js:16)
    at Recaptcha.js:26
```

even with `external-load`

Comment (datitisev) [reply js/src/forum/components/Recaptcha.js:25]: Hm, intersting. It's fine then, although not great.

Comment (Nearata) [reply js/src/forum/components/Recaptcha.js:25]: after the promise, `window.recaptcha` is still `undefined`. That's why i added the interval.
